#!/bin/bash
echo "This tool will assist with getting you the correct version of the script"
sleep .5
echo "Type the number associated to the version you'd like to use"
echo "------------------------------------------------------------------------------"
echo "1) Standard Setup Script"
echo "2) Beta Setup Script"
printf ">: "
read userResponse

commandInstalled=$(xcode-select -p)

if [ $commandInstalled == 0 ]; then
    echo "You'll have to install git first, so accept the next prompt, thank you."
    sleep 1
    git clone
    read -p "Press Enter when you have installed git [ENTER]>: "

fi


if [ $userResponse == '1' ]; then
    echo "Setting the download location to your desktop"
    sleep 1
    cd Desktop
    echo "Downloading the latest version of the Mac Script"
    git clone https://github.com/mrneilj/MacScript
    echo "Download Successful, starting MacScript"
    sleep 1
    cd MacScript
    ./MacScript
elif [ $userResponse == '2' ]; then
    echo "Setting the download location to your desktop"
    sleep 1
    cd Desktop
    echo "Downloading the beta version of the Mac Script"
    git clone https://github.com/mrneilj/MacScript
    echo "Download Successful, starting MacScript"
    sleep 1
    cd MacScript
    ./MacScript
else
    echo "Incorrect command detected, closing window, try running the program again."
fi

    
