#!/bin/bash
clear
echo "Checking to make sure Command line tools are installed"
sleep .5
echo "If a pop up appears, select install and proceed"
sleep 1
xcode-select --install
read -p "If / Once command lines tools have been installed press enter [ENTER]"

echo "This tool will assist with getting you the correct version of the script"
sleep .5
echo "Type the number associated to the version you'd like to use"
echo "------------------------------------------------------------------------------"
echo "1) Standard Setup Script"
echo "2) Beta Setup Script"
printf ">: "
read userResponse



#commandInstalled=$(xcode-select -p)

#if [ $commandInstalled == 0 ]; then
#    echo "You'll have to install git first, so accept the next prompt, thank you."
#    sleep 1
#    xcode-select --install    
#    read -p "Press Enter when you have installed git [ENTER]>: "
#fi


if [ $userResponse == '1' ]; then
    echo "Setting the download location to your shared folder"
    sleep 1
    cd /Users/Shared
    echo "Downloading the latest version of the Mac Script"
    sleep 1
    git clone https://github.com/mrneilj/MacScript.git
    sleep 1
    mv Users/Shared/MacScript/MacScript /Users/Shared
    echo "------------------------------------------------------------------------------"
    echo "Download Successful, starting MacScript"
    sleep 2
    ./MacScript
elif [ $userResponse == '2' ]; then
    echo "Setting the download location to your shared folder"
    sleep 1
    cd /Users/Shared
    echo "Downloading the beta version of the Mac Script"
    git clone -b testing --single-branch https://github.com/mrneilj/MacScript.git
    sleep 1
    mv Users/Shared/MacScript/MacScript /Users/Shared
    echo "------------------------------------------------------------------------------"
    echo "Download Successful, starting MacScript BETA"
    sleep 2
    ./MacScript
else
    echo "Incorrect command detected, closing window, try running the program again."
fi

    
